version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./data/prometheus:/promtheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
  # node-exporter:
  #   image: prom/node-exporter:latest
  #   ports:
  #     - 9100:9100
  # grafana:
  #   image: grafana/grafana
  #   volumes: 
  #     - ./data/grafana:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000