global: 
  external_labels: 
    monitor: test-monitor
  scrape_interval: 20s
scrape_configs: 
  - job_name: prometheus
    static_configs: 
      - targets: 
        - "localhost:9090"
  - job_name: node-exporter
    static_configs:
      - targets:
        - "node-exporter:9100"
  - job_name: mysqld-exporter
    static_configs:
      - targets:
        - "mysqld-exporter:9104"
        labels:
          alias: mysqld-db-exporter